
import { GoogleGenAI } from "@google/genai";
import { AspectRatio } from '../types';

if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export async function generateWallpaper(prompt: string, aspectRatio: AspectRatio): Promise<string> {
    try {
        const enhancedPrompt = `${prompt}, high resolution wallpaper, digital art, stunning, vibrant colors`;
        
        const response = await ai.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt: enhancedPrompt,
            config: {
                numberOfImages: 1,
                outputMimeType: 'image/png',
                aspectRatio,
            },
        });

        if (response.generatedImages && response.generatedImages.length > 0) {
            const image = response.generatedImages[0];
            if (image.image?.imageBytes) {
                return image.image.imageBytes;
            }
        }
        
        throw new Error("No image was generated by the API.");

    } catch (error) {
        console.error("Error generating wallpaper with Gemini:", error);
        throw new Error("The AI failed to generate an image. Please try a different prompt.");
    }
}
